# fly.toml app configuration file generated for assignment-shah-faisal on 2025-02-22T22:59:08+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'assignment-shah-faisal'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
